### ISSUE TITLE
Question about units.

### ISSUE THREAD

**Issue by grinsted** [tamsinedwards/emulandice#1]
Congrats on the paper.  Great work 😊 

I am trying to understand the units of especially the SLE column of some of the files. Specifically i am looking at this: 
proj_MAIN_TIMESERIES/projections_FAIR_SSP585.csv

and to ensure i understand the file i am trying to reproduce a plot that looks like this: proj_MAIN_TIMESERIES/ED_hist_SSP585_ALL.pdf

But it is not working - so i guess that i am misinterpreting the SLE column. Please help. 

(Also what is the baseline for the GSAT columns?)

**Comment by tamsinedwards** [comment]
Thanks Aslak! 

All units are cm.

The ED_hist plot you mention is not in the paper, it was just there as legacy so is therefore not documented. The histograms in these are the raw MIP ensembles, while the CSV you are plotting is the emulated Monte Carlo sample (i.e. they should not match!). 

The MC samples are shown in Figure 3 for the glacier and Antarctic totals, so you could try reproducing those. But if you want to exactly reproduce any numbers or figures you should use the 2100 not TIMESERIES files, because those have the higher N I used at 2100. The TIMESERIES data are only shown in the timeseries panel of Figure 3.

The GSAT baseline is 2015.

**Comment by grinsted** [comment]
Thank you. That is good to know. I will keep working with the time series files is because i'd like to have the 2016-2100 average of GSAT. It also seems that the a given sample index corresponds to the same set of model params between different forcing scenarios. At least sample=301 is a GrIS outlier in all the projection_* files. So it appears there is some really useful info about uncertainty co-variance in the projection files. I assume that it also holds covariance info between contributors.

**Comment by tamsinedwards** [comment]
Yes, the whole point is that we use the same GSAT value for each region. The index corresponds to the GSAT value, as you say. The model parameters (kappa etc) and emulator uncertainty are only sampled once per GSAT, to facilitate this book-keeping.
